"""Add assignment history table

Revision ID: 48871d03964b
Revises: 47871d03964a
Create Date: 2026-01-18 21:26:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '48871d03964b'
down_revision = '47871d03964a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_history',
                    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('assigned_at', sa.DateTime(), nullable=False),
                    sa.Column('notes', sa.Text(), nullable=True),
                    sa.Column('child_item_id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('from_parent_item_id', postgresql.UUID(as_uuid=True), nullable=True),
                    sa.Column('to_parent_item_id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('assigned_by', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='RESTRICT'),
                    sa.ForeignKeyConstraint(['child_item_id'], ['child_items.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['from_parent_item_id'], ['parent_items.id'], ondelete='RESTRICT'),
                    sa.ForeignKeyConstraint(['to_parent_item_id'], ['parent_items.id'], ondelete='RESTRICT'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(
        op.f('ix_assignment_history_assigned_at'),
        'assignment_history',
        ['assigned_at'],
        unique=False)
    op.create_index(
        op.f('ix_assignment_history_assigned_by'),
        'assignment_history',
        ['assigned_by'],
        unique=False)
    op.create_index(
        op.f('ix_assignment_history_child_item_id'),
        'assignment_history',
        ['child_item_id'],
        unique=False)
    op.create_index(
        op.f('ix_assignment_history_from_parent_item_id'),
        'assignment_history',
        ['from_parent_item_id'],
        unique=False)
    op.create_index(
        op.f('ix_assignment_history_to_parent_item_id'),
        'assignment_history',
        ['to_parent_item_id'],
        unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_assignment_history_to_parent_item_id'),
        table_name='assignment_history')
    op.drop_index(
        op.f('ix_assignment_history_from_parent_item_id'),
        table_name='assignment_history')
    op.drop_index(
        op.f('ix_assignment_history_child_item_id'),
        table_name='assignment_history')
    op.drop_index(
        op.f('ix_assignment_history_assigned_by'),
        table_name='assignment_history')
    op.drop_index(
        op.f('ix_assignment_history_assigned_at'),
        table_name='assignment_history')
    op.drop_table('assignment_history')
    # ### end Alembic commands ###
